[[Xorg_libxcb]]
arch = "aarch64"
git-tree-sha1 = "e6be565fbf15b6026968148d454197a76e43a814"
libc = "musl"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "a9523e5b2a2e1234eeb862506ac4c9dddcd106a367ae83cafd2be04484bfbd5c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.13.0+1/Xorg_libxcb.v1.13.0.aarch64-linux-musl.tar.gz"
[[Xorg_libxcb]]
arch = "aarch64"
git-tree-sha1 = "f1c48138b75400dd263fb1e0b2a36c0f7ac1271a"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "c4585cae556aff7f753099208566d8d7dfc6346bbec6f94335aa5328a65866d1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.13.0+1/Xorg_libxcb.v1.13.0.aarch64-linux-gnu.tar.gz"
[[Xorg_libxcb]]
arch = "x86_64"
git-tree-sha1 = "7077f082fd43a60a2c161c32d1d060fd26d4553a"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "592096410c9e85fd8e020cbfdb0bd9b7d286f291d7538c2695b4b20cad9a05b1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.13.0+1/Xorg_libxcb.v1.13.0.x86_64-linux-gnu.tar.gz"
[[Xorg_libxcb]]
arch = "powerpc64le"
git-tree-sha1 = "7a7afddef6165197ee085c2664f79ba5f972e4dd"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "6c52a3638c78740aab5a85d24d9a16496ee6d0999d7835aae283e43bea51d136"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.13.0+1/Xorg_libxcb.v1.13.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libxcb]]
arch = "x86_64"
git-tree-sha1 = "a23857d97a1c2771c339d55a2ecbf8da665d5f3c"
os = "freebsd"

    [[Xorg_libxcb.download]]
    sha256 = "f9c7a493a9beb0361c790f0ab5ad99bac1b3208f020e80fed5835105d8bc43e5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.13.0+1/Xorg_libxcb.v1.13.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libxcb]]
arch = "i686"
git-tree-sha1 = "e8b401c44c11d843d10de2195bd18a20bb4e5b9b"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "35eab64bb8a14560f2fe179e2bdc09e32bf72675661ede455d246a88a30288dd"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.13.0+1/Xorg_libxcb.v1.13.0.i686-linux-gnu.tar.gz"
[[Xorg_libxcb]]
arch = "i686"
git-tree-sha1 = "5624ac50a2fb547d012af5b0bb3cbbe14eb4933d"
libc = "musl"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "644385b372ff3311c079e1f97f09f2558e7ac45ff6cb7bbb02916f208a5aa153"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.13.0+1/Xorg_libxcb.v1.13.0.i686-linux-musl.tar.gz"
[[Xorg_libxcb]]
arch = "armv7l"
git-tree-sha1 = "cc454d03bb0bafb083a2f2d8b89c695e0bb33657"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "d51490d19354a739441f183ae7d4cf0216faeacb1e7358148e1a06981716a493"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.13.0+1/Xorg_libxcb.v1.13.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libxcb]]
arch = "x86_64"
git-tree-sha1 = "b51ced8eb11e4181647c71dc436e8af5a9d94455"
libc = "musl"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "42f991f744358f19551a911145a2a498477fc11c8753d9bbd23b1c0ffa3e44c2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.13.0+1/Xorg_libxcb.v1.13.0.x86_64-linux-musl.tar.gz"
[[Xorg_libxcb]]
arch = "armv7l"
git-tree-sha1 = "9f78ec4cf44cb13ff57eba2b428b9818db73c2c4"
libc = "musl"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "77073b58d2eb2adf0dfc9bb4a60d471c8f2ccd050de80572b0435b5b5cca7264"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.13.0+1/Xorg_libxcb.v1.13.0.armv7l-linux-musleabihf.tar.gz"
