[[Xorg_libxcb]]
arch = "aarch64"
git-tree-sha1 = "81e33103820f21745bf6a0063706ad49243d103e"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "386be405809fabc011dc7085c7b5fc86e150ccb5b4e99980c82a5603beac9498"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.0+1/Xorg_libxcb.v1.17.0.aarch64-linux-gnu.tar.gz"
[[Xorg_libxcb]]
arch = "aarch64"
git-tree-sha1 = "fe5b59e84bf56456681439ad509cfa3f773792e1"
libc = "musl"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "56323d0f66562cdad86d42eaeeb41497bd6bfb6842db21aa6b81d8eb87c14099"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.0+1/Xorg_libxcb.v1.17.0.aarch64-linux-musl.tar.gz"
[[Xorg_libxcb]]
arch = "aarch64"
git-tree-sha1 = "75a2f0fc40a44429dd9c7ebe4211d4e63f27c3ab"
os = "freebsd"

    [[Xorg_libxcb.download]]
    sha256 = "a7efdf8b8c325a66cb61c40bf3545cc72f09ded1a25fac9a42bd77c35d90abc5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.0+1/Xorg_libxcb.v1.17.0.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libxcb]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4993be4603ba8c904403091c16ceac85ab5647eb"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "b5fc0955e43d972cc6b57f7863af2b8de1766f32f4daca9e2e7d56ffbcd86f46"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.0+1/Xorg_libxcb.v1.17.0.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libxcb]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c7d8480fd3ee1dfe1d610edc3a7ef97092daff3b"
libc = "musl"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "eeb43765ea9267a2cdc8a8bff483941eaac028d56fcd4c4c2188e64e7eebb816"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.0+1/Xorg_libxcb.v1.17.0.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libxcb]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "379353c360ebab7c0db449c90ed054264ce21a1a"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "ed5d9022b3e3e676d6f128389f1810ead7a7d4e36a09cdc88121f5db22c9e4c9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.0+1/Xorg_libxcb.v1.17.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libxcb]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9845a017a9f343ad0a480f4d8dcb6ad227cb273e"
libc = "musl"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "17509403851c90c24c540325bffc7d3067d63e81aafcab309eb51f5f8a5e6f66"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.0+1/Xorg_libxcb.v1.17.0.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libxcb]]
arch = "i686"
git-tree-sha1 = "7c73b776274ac35af34c45cbb5b9cce711eecf8c"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "1fd9455139c19d72d96453430684a8ff52ab7220b0e8b6034b50a4590617b5f2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.0+1/Xorg_libxcb.v1.17.0.i686-linux-gnu.tar.gz"
[[Xorg_libxcb]]
arch = "i686"
git-tree-sha1 = "e76df66edb78ffbda4ce98904cd5ba828b9adbb8"
libc = "musl"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "b332cb12c4310bf4690da2262d2dc183efcd5a9f9a36f08bd59d02b1d48e2965"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.0+1/Xorg_libxcb.v1.17.0.i686-linux-musl.tar.gz"
[[Xorg_libxcb]]
arch = "powerpc64le"
git-tree-sha1 = "f29d80a69557dd6fc37057d239717b8df0dab97a"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "cdcde2fa9ffeeeca6da3622c28dd9dafa4dc0232fb6f499e91a4531d3cdbae43"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.0+1/Xorg_libxcb.v1.17.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libxcb]]
arch = "x86_64"
git-tree-sha1 = "2bb2b0081086bcb24e6bd287b7416b6b61d856a3"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "e28454aafe960afd0bc482fd0c011c345d016b6ae99d53ccca29830921d6aae6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.0+1/Xorg_libxcb.v1.17.0.x86_64-linux-gnu.tar.gz"
[[Xorg_libxcb]]
arch = "x86_64"
git-tree-sha1 = "3fd2884f0dcc63a1abb05b74547cd48d7eeda23d"
libc = "musl"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "56f94086b27e5effaa1f574eed44c9fef283d48551a73478f6314b76c378483c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.0+1/Xorg_libxcb.v1.17.0.x86_64-linux-musl.tar.gz"
[[Xorg_libxcb]]
arch = "x86_64"
git-tree-sha1 = "6408d044a7fb17a6800349df78bc697a2774a4d7"
os = "freebsd"

    [[Xorg_libxcb.download]]
    sha256 = "6db5a8873557e29a7e9feff8009cb5df198d53a00e3a1f9cc54d3b9289d5c19f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.0+1/Xorg_libxcb.v1.17.0.x86_64-unknown-freebsd.tar.gz"
