[[Xorg_libxcb]]
arch = "aarch64"
git-tree-sha1 = "6d5f0641e628bee83005b26ca1088cfca53b6332"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "2e8be9b0617a941a26751bb5ea02367e56a8a14190b41a01b79cbcfea2c94ee9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.1+0/Xorg_libxcb.v1.17.1.aarch64-linux-gnu.tar.gz"
[[Xorg_libxcb]]
arch = "aarch64"
git-tree-sha1 = "285d4b1c48f6768130d0277956ef83306e2648f6"
libc = "musl"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "0238fce51c0fc588e6e52eff659ff7486fce88821ea9a725b1d4c8d2acc2de9f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.1+0/Xorg_libxcb.v1.17.1.aarch64-linux-musl.tar.gz"
[[Xorg_libxcb]]
arch = "aarch64"
git-tree-sha1 = "db76f3ba2a4d2fbf4a5d74268cfcf9ff6471908e"
os = "freebsd"

    [[Xorg_libxcb.download]]
    sha256 = "3f59bd36728c8868a9ffe98773c39ee84573f4d9f1e57b880144b6fc76e98321"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.1+0/Xorg_libxcb.v1.17.1.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libxcb]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7e9fe36f50428f8856023b1f796a02721f985c1d"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "56da248e385a7c0646750a32cd8f40012c6b6df2ed5460289008cd48638505e9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.1+0/Xorg_libxcb.v1.17.1.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libxcb]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "68f94d91cb679ffe4f9cb4e8658208c552db84fc"
libc = "musl"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "9b308a4b27d4629724ce1cf443fc4268c45de4136df430e6cd44eedbf4c1f320"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.1+0/Xorg_libxcb.v1.17.1.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libxcb]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "92667245e08b825b217514dc03ab2a5be277c7d0"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "871b01d5a92b6a128c8c1b648725b3fb75e8a3189a28e1473230f6a4453df143"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.1+0/Xorg_libxcb.v1.17.1.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libxcb]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9adef2780258bde35309705bb853c760e5e85d0a"
libc = "musl"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "513795b86bb62912fca3f88f839d87c5f8040f8b141a13f0dcc8fb2280ecf383"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.1+0/Xorg_libxcb.v1.17.1.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libxcb]]
arch = "i686"
git-tree-sha1 = "3855318265ad717226649b4ccf6d1dd75769c422"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "58e13a16df4f0833ffd284460d86697b7b5312c3ad84ba7f98790d91c451f690"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.1+0/Xorg_libxcb.v1.17.1.i686-linux-gnu.tar.gz"
[[Xorg_libxcb]]
arch = "i686"
git-tree-sha1 = "4bdc7b3d2ca47e6f6806784b2bbaa9366e467dfb"
libc = "musl"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "51b0231fecf58680fa4e4dff0f45a65fa26d07c4ecb57142776831d596f68971"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.1+0/Xorg_libxcb.v1.17.1.i686-linux-musl.tar.gz"
[[Xorg_libxcb]]
arch = "powerpc64le"
git-tree-sha1 = "219a45672b853511fe03a2841b2a8f5816d4e445"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "5aaa824007aeb190e684c3c1758f6d9efe0db71de46d06a32f24191efc826f60"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.1+0/Xorg_libxcb.v1.17.1.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libxcb]]
arch = "riscv64"
git-tree-sha1 = "70c350bd5e9e0f7639896ca16bf07f6c51a32fbb"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "85b89a67c8d022d37246840212056ede45db31191f818ac2e9079bd07e216160"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.1+0/Xorg_libxcb.v1.17.1.riscv64-linux-gnu.tar.gz"
[[Xorg_libxcb]]
arch = "x86_64"
git-tree-sha1 = "299dd9a174ebc497df2cf4d30f1c6d10948c60ef"
libc = "glibc"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "7c8616eef813a1c87b4cec3b0bfcb696d7f331e2c3455a1ed94dc377745209aa"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.1+0/Xorg_libxcb.v1.17.1.x86_64-linux-gnu.tar.gz"
[[Xorg_libxcb]]
arch = "x86_64"
git-tree-sha1 = "2d61042ea04700752392255587e849b8f971f0dd"
libc = "musl"
os = "linux"

    [[Xorg_libxcb.download]]
    sha256 = "f8fa71afa883479e3136a1472cd48043aa7034efc2489b416cc2a241c2eeb37d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.1+0/Xorg_libxcb.v1.17.1.x86_64-linux-musl.tar.gz"
[[Xorg_libxcb]]
arch = "x86_64"
git-tree-sha1 = "664f5dec1f35098192d06d8bde349ca70f9c2f81"
os = "freebsd"

    [[Xorg_libxcb.download]]
    sha256 = "a503d8d8a9e0fc913dc6ca7b02a9127379d04538559a81071f0a8ab2f7c1c500"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libxcb_jll.jl/releases/download/Xorg_libxcb-v1.17.1+0/Xorg_libxcb.v1.17.1.x86_64-unknown-freebsd.tar.gz"
